---

- hosts: all
  become: true
  tasks:

  - name: install apache package 
    package: 
      name: "{{ apache_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"